- app/models/cart_product.rb
- app/models/customer.rb
- app/models/order_detail.rb
- app/models/order_list.rb
- app/models/product.rb
- app/models/product_genre.rb
- app/models/shipping_address.rb
> [add]has_many,belongs_to

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/customers.scss
- app/controllers/admins/products_controller.rb
- app/controllers/customers/products_controller.rb
- app/models/product.rb
- app/views/customers/products/index.html.erb
- app/views/customers/products/show.html.erb
- app/views/customers/products/top.html.erb
- app/views/layouts/_sidebar.html.erb
- db/seeds.rb
・会員の商品ページ途中まで
・bootstrap等をapplication.js、cssにも記述
> [add]product

- app/controllers/customers/cart_products_controller.rb
- app/views/customers/cart_products/show.html.erb
CartProduct
ビュー、コントローラー更新しました。
> [add]CartProduct

- app/views/customers/confirmations/new.html.erb
- app/views/customers/mailer/confirmation_instructions.html.erb
- app/views/customers/mailer/email_changed.html.erb
- app/views/customers/mailer/password_change.html.erb
- app/views/customers/mailer/reset_password_instructions.html.erb
- app/views/customers/mailer/unlock_instructions.html.erb
- app/views/customers/passwords/edit.html.erb
- app/views/customers/passwords/new.html.erb
- app/views/customers/registrations/edit.html.erb
- app/views/customers/registrations/new.html.erb
- app/views/customers/sessions/new.html.erb
- app/views/customers/shared/_error_messages.html.erb
- app/views/customers/shared/_links.html.erb
- app/views/customers/unlocks/new.html.erb
> [add]devise view

- app/controllers/admins/product_genres_controller.rb
- app/controllers/product_genres_controller.rb
- app/views/admins/product_genres/edit.html.erb
- app/views/admins/product_genres/index.html.erb
- app/views/layouts/application.html.erb
> [add]adminviews

- app/controllers/customers/confirmations_controller.rb
- app/controllers/customers/omniauth_callbacks_controller.rb
- app/controllers/customers/passwords_controller.rb
- app/controllers/customers/registrations_controller.rb
- app/controllers/customers/sessions_controller.rb
- app/controllers/customers/unlocks_controller.rb
- app/views/customers/registrations/new.html.erb
- config/routes.rb
> [fix]devise view

- app/controllers/application_controller.rb
- app/views/customers/cart_products/show.html.erb
- app/views/customers/registrations/new.html.erb
- db/schema.rb
application_controller.rb
・サインアップ後とサインイン後のリダイレクト先を商品一覧ページ登録。
registrations/new.html.erb(views)
mail_address→emailに変更。
> [add]devise

- app/controllers/customers/cart_products_controller.rb
- app/controllers/customers/order_lists_controller.rb
- app/views/customers/cart_products/show.html.erb
CartProduct
コントローラークリエイト追加。
OrderList
コントローラーアクション追加。
> [update]CartProducts

- app/controllers/customers/order_lists_controller.rb
- app/views/customers/order_lists/input.html.erb
> [update]OrderList

- app/controllers/customers/cart_products_controller.rb
- app/views/customers/cart_products/index.html.erb
- app/views/customers/order_lists/input.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
ルーティング一部変更
cart_product order_list更新
> [update]routes cart_product order_list

- app/assets/stylesheets/application.scss.erb
- app/controllers/admins/order_details_controller.rb
- app/controllers/admins/order_lists_controller.rb
- app/controllers/admins/sessions_controller.rb
- app/helpers/admins/order_lists_helper.rb
- app/helpers/admins/products_helper.rb
- app/models/customer.rb
- app/models/order_detail.rb
- app/models/order_list.rb
- app/models/product.rb
- app/models/product_genre.rb
- app/views/admins/customers/index.html.erb
- app/views/admins/order_lists/index.html.erb
- app/views/admins/order_lists/show.html.erb
- app/views/admins/product_genres/index.html.erb
- app/views/admins/products/edit.html.erb
- app/views/admins/products/index.html.erb
- app/views/admins/products/show.html.erb
- app/views/layouts/application.html.erb
- config/application.rb
- config/locales/ja.yml
> [add]adminorder

- app/assets/stylesheets/application.scss.erb
- app/models/cart_product.rb
- config/routes.rb
> [update]routes

- app/controllers/customers/products_controller.rb
- app/views/customers/products/show.html.erb
- config/routes.rb
> [update]cart

- app/controllers/customers/order_lists_controller.rb
- app/views/customers/order_lists/index.html.erb
> [add]会員注文履歴

- app/controllers/customers/cart_products_controller.rb
- app/models/cart_product.rb
- app/views/customers/cart_products/index.html.erb
> [update]cart_products

- app/controllers/application_controller.rb
- app/controllers/customers_controller.rb
- app/views/customers/edit.html.erb
- app/views/customers/mypage.html.erb
- app/views/customers/shared/_links.html.erb
- app/views/customers/withdraw.html.erb
- config/routes.rb
> [fix]customer view

- app/controllers/customers/order_lists_controller.rb
- app/views/customers/order_lists/index.html.erb
- app/views/customers/order_lists/show.html.erb
- app/views/customers/products/show.html.erb
> Umeharamasayo8

- Gemfile
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss.erb
- app/controllers/customers/order_lists_controller.rb
- app/helpers/customers/order_lists_helper.rb
- app/views/customers/order_lists/index.html.erb
- app/views/customers/order_lists/show.html.erb
- app/views/customers/products/index.html.erb
- app/views/layouts/application.html.erb
> Umeharamasayo9

- app/controllers/application_controller.rb
- app/controllers/customers/cart_products_controller.rb
- app/controllers/customers/order_lists_controller.rb
- app/views/customers/cart_products/index.html.erb
- app/views/customers/order_lists/confirm.html.erb
- app/views/customers/order_lists/input.html.erb
- config/routes.rb
> [update]order

- app/controllers/customers/cart_products_controller.rb
- app/controllers/customers/order_lists_controller.rb
- app/views/customers/order_lists/confirm.html.erb
- app/views/customers/order_lists/input.html.erb
> [fix]order_list

- app/controllers/customers/cart_products_controller.rb
- app/controllers/customers/order_lists_controller.rb
- app/views/customers/cart_products/index.html.erb
- app/views/customers/order_lists/show.html.erb
- config/routes.rb
> [update]order_list

- app/assets/javascripts/application.js
- app/assets/javascripts/customers/shipping_addresses.coffee
- app/controllers/customers/shipping_addresses_controller.rb
- app/models/shipping_address.rb
- app/views/customers/shipping_addresses/index.html.erb
> [add]配送先住所自動

- app/assets/stylesheets/application.scss.erb
- app/views/customers/products/show.html.erb
> [add]デザイン変更

- app/controllers/customers/order_lists_controller.rb
- app/views/customers/cart_products/index.html.erb
- app/views/customers/order_lists/confirm.html.erb
- app/views/customers/order_lists/input.html.erb
- app/views/customers/order_lists/show.html.erb
> [add]cart,order

- app/controllers/customers/registrations_controller.rb
- app/controllers/customers/sessions_controller.rb
> [fix]コントローラー
